### ISSUE TITLE
CustomizeWithAttribute class is sealed

### ISSUE THREAD

**Issue by PaJomantas** [ObjectivityLtd/AutoFixture.XUnit2.AutoMock#37]
Hello, I noticed that in a commit [Switch from .ruleset to .editorconfig and fix static code analysis issues](https://github.com/ObjectivityLtd/AutoFixture.XUnit2.AutoMock/pull/36/commits/28153447bce72bae07ee4a982b5a3f2d3ffbec5a) you added a `sealed` modifier for `CustomizeWithAttribute` class, so now it's impossible to inherit from it. Was this done by an accident or on purpose, since I can't find any comments regarding this change.

**Comment by piotrzajac** [comment]
Hi @PaJomantas. It was by design. I should have sealed the functionality of this attribute originally when I designed it. What kind of functionality are you missing that you need to extend the `CustomizeWithAttribute`?

**Comment by PaJomantas** [comment]
I had a following scenario (simplified)

```
public class MyEntity 
{
   public ICollection<int> Ints { get; set; } = new List<int>();
}

public class EmptyListCustomization : ICustomization
{
   public void Customize(IFixture fixture)
   {
       fixture.Register<ICollection<int>>(() => new List<int>());
   }
}

public class EmptyListEntityAttribute : CustomizeWithAttribute
    {
    public EmptyListEntityAttribute() : base(typeof(EmptyListCustomization)) { }
    }
```


Which allowed me to use the following attribute in tests:
```
[Theory]
[AutoMockData]
public void TestScenario_TestOutcome([EmptyListEntity] MyEntity)
```

Instead of:
```
[Theory]
[AutoMockData]
public void TestScenario_TestOutcome([CustomizeWith(typeof(EmptyListCustomization))] MyEntity)
```

I can still achieve the same functionality, but it was just "sugar" when `CustomizeWithAttribute` was inheritable

**Comment by piotrzajac** [comment]
I agree, the tool should not prevent bounding customization with attribute for the ease of use. I plan to revert that change together with introducing generic `CustomizeWithAttribute` hopefully next month.

**Comment by sm-g** [comment]
@piotrzajac same for https://github.com/Accenture/AutoFixture.XUnit2.AutoMock/blob/master/src/Objectivity.AutoFixture.XUnit2.AutoMoq/Attributes/AutoMockDataAttribute.cs (etc)

I want to add some customizations for Fixture for every test marked with `[MyAutoMockData]` and have to copy-paste src instead of subclassing

**Comment by piotrzajac** [comment]
@sm-g Please open a separate issue and explain in details as it looks seems to be irrelevant to `CustomizeWithAttribute` classes.
